name: Spellcheck Action
on: 
  push:
    paths:
      - '*.md'

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
      with:
        egress-policy: audit

    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - uses: rojopolis/spellcheck-github-actions@3b1fb41a7fa47bf0a17a49c347382abec41743df # 0.27.0
      name: Spellcheck
      with:
        source_files: '*.md'
        task_name: Markdown
