name: Spellcheck Action
on: 
  push:
    paths:
      - '*.md'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.27.0
      name: Spellcheck
      with:
        source_files: '*.md'
        task_name: Markdown
