name: Verify Signed Commits

on:
  pull_request:
  push:

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Verify Signed Commits
      run: |
        # Determine the range of commits to check
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For pull requests, compare with the base branch
          range="${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}"
        else
          # For pushes, use the pushed commits
          range="${{ github.event.before }}...${{ github.event.after }}"
        fi

        # Verify signatures on the commits in the range
        commits=$(git rev-list $range)
        for commit in $commits; do
          if ! git verify-commit $commit &> /dev/null; then
            echo "::error::Commit $commit is not signed"
            exit 1
          fi
        done
